#!/usr/bin/env python3
"""
Device Onboarding API Service

Primary Key: Device ID (auto-generated by NetBox)
- Manual Onboarding: IP address required
- DHCP Onboarding (future): MAC address required

Usage:
    python onboarding_api.py

Endpoints:
    POST /api/onboard      - Manual onboarding with IP
    POST /api/onboard/dhcp - DHCP onboarding with MAC (future)
"""

from flask import Flask, request, jsonify
from flask_cors import CORS
import requests
from requests.adapters import HTTPAdapter
import re
import os
import io
import csv
import time
import uuid
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime
from cryptography.fernet import Fernet
import logging

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

app = Flask(__name__)
CORS(app)

# Configuration
NETBOX_URL = os.environ.get('NETBOX_URL', 'http://localhost:8000')
NETBOX_TOKEN = os.environ.get('NETBOX_TOKEN', '0123456789abcdef0123456789abcdef01234567')
ENCRYPTION_KEY = os.environ.get('NETBOX_DEVICE_ENCRYPTION_KEY', 'XPmjtY0wwxQbD0ezEMDhGlAo2_JGXb6yB4yp5I-MnGA=')

HEADERS = {
    'Authorization': f'Token {NETBOX_TOKEN}',
    'Content-Type': 'application/json'
}

# Create a session with connection pooling (sized for 15 bulk workers + single requests)
session = requests.Session()
session.headers.update(HEADERS)
adapter = HTTPAdapter(pool_connections=20, pool_maxsize=20)
session.mount('http://', adapter)
session.mount('https://', adapter)

# Bulk onboard configuration
BULK_MAX_WORKERS = int(os.environ.get('BULK_MAX_WORKERS', '15'))
BULK_MAX_DEVICES = int(os.environ.get('BULK_MAX_DEVICES', '20000'))
bulk_lock = threading.Lock()
bulk_in_progress = False

# Batch tracking: persists in memory so user can close tab and come back
# Key: batch_id (UUID), Value: batch state dict
_batches = {}
_batches_lock = threading.Lock()

# Regex patterns
MAC_PATTERN = re.compile(r'^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$|^([0-9A-Fa-f]{4}\.){2}([0-9A-Fa-f]{4})$')

# Use Python's ipaddress module for reliable IP validation
import ipaddress


def detect_ip_version(ip):
    """Detect if IP is IPv4 or IPv6 using Python's ipaddress module"""
    try:
        addr = ipaddress.ip_address(ip)
        if isinstance(addr, ipaddress.IPv4Address):
            return 'ipv4'
        elif isinstance(addr, ipaddress.IPv6Address):
            return 'ipv6'
    except ValueError:
        pass
    return None


def is_valid_mac(mac):
    """Validate MAC address format"""
    return bool(MAC_PATTERN.match(mac))


def normalize_mac(mac):
    """Normalize MAC address to AA:BB:CC:DD:EE:FF format"""
    mac_clean = re.sub(r'[.:-]', '', mac).upper()
    return ':'.join(mac_clean[i:i+2] for i in range(0, 12, 2))


def encrypt_password(password):
    """Encrypt password using Fernet"""
    try:
        key = ENCRYPTION_KEY
        if isinstance(key, str):
            key = key.encode()
        cipher = Fernet(key)
        return cipher.encrypt(password.encode()).decode()
    except Exception:
        return password


def check_ip_exists(ip_address):
    """Check if IP address already exists in NetBox"""
    try:
        response = session.get(
            f"{NETBOX_URL}/api/ipam/ip-addresses/",
            params={'address': ip_address}
        )
        if response.status_code == 200:
            data = response.json()
            if data['count'] > 0:
                result = data['results'][0]
                device_name = None
                device_id = None
                if result.get('assigned_object') and result['assigned_object'].get('device'):
                    device_name = result['assigned_object']['device'].get('name')
                    device_id = result['assigned_object']['device'].get('id')
                return {
                    'exists': True,
                    'ip_id': result['id'],
                    'address': result['address'],
                    'device_name': device_name,
                    'device_id': device_id
                }
        return {'exists': False}
    except Exception as e:
        return {'exists': False, 'error': str(e)}


def check_ip_device_reachable(ip_address):
    """
    Check if IP exists and if the device is reachable.
    Used for DHCP to allow IP reassignment only if device is down.
    """
    try:
        # First check if IP exists
        ip_check = check_ip_exists(ip_address)
        if not ip_check['exists']:
            return {'exists': False, 'can_reassign': True}

        device_id = ip_check.get('device_id')
        if not device_id:
            # IP exists but not assigned to device - can reassign
            return {
                'exists': True,
                'can_reassign': True,
                'ip_id': ip_check.get('ip_id'),
                'reason': 'IP not assigned to any device'
            }

        # Get device details including reachable status
        response = session.get(f"{NETBOX_URL}/api/dcim/devices/{device_id}/")
        if response.status_code == 200:
            device = response.json()
            custom_fields = device.get('custom_fields', {})
            reachable = custom_fields.get('reachable', None)

            # If reachable is True (device is up), don't allow reassignment
            if reachable is True:
                return {
                    'exists': True,
                    'can_reassign': False,
                    'device_id': device_id,
                    'device_name': device.get('name'),
                    'device_reachable': True,
                    'ip_id': ip_check.get('ip_id'),
                    'reason': 'Device is reachable (up)'
                }
            else:
                # Device is down or reachable status unknown - allow reassignment
                return {
                    'exists': True,
                    'can_reassign': True,
                    'device_id': device_id,
                    'device_name': device.get('name'),
                    'device_reachable': reachable,
                    'ip_id': ip_check.get('ip_id'),
                    'reason': 'Device is down or status unknown'
                }

        return {'exists': True, 'can_reassign': True, 'reason': 'Could not get device status'}
    except Exception as e:
        return {'exists': False, 'can_reassign': True, 'error': str(e)}


def check_device_exists(device_name):
    """Check if device name already exists in NetBox"""
    try:
        response = session.get(
            f"{NETBOX_URL}/api/dcim/devices/",
            params={'name': device_name}
        )
        if response.status_code == 200:
            data = response.json()
            if data['count'] > 0:
                result = data['results'][0]
                return {
                    'exists': True,
                    'device_id': result['id'],
                    'device_name': result['name'],
                    'primary_ip': result.get('primary_ip4', {}).get('address') if result.get('primary_ip4') else None
                }
        return {'exists': False}
    except Exception as e:
        return {'exists': False, 'error': str(e)}


def check_mac_exists(mac_address):
    """Check if MAC address already exists in NetBox interfaces"""
    try:
        normalized_mac = normalize_mac(mac_address)
        response = session.get(
            f"{NETBOX_URL}/api/dcim/interfaces/",
            params={'mac_address': normalized_mac}
        )
        if response.status_code == 200:
            data = response.json()
            if data['count'] > 0:
                result = data['results'][0]
                return {
                    'exists': True,
                    'interface_id': result['id'],
                    'mac_address': result['mac_address'],
                    'device_id': result.get('device', {}).get('id'),
                    'device_name': result.get('device', {}).get('name')
                }
        return {'exists': False}
    except Exception as e:
        return {'exists': False, 'error': str(e)}


# =============================================================================
# CORE ONBOARDING LOGIC (reusable by single + bulk endpoints)
# =============================================================================
def _onboard_manual(data):
    """
    Core manual onboarding logic. Returns (result_dict, status_code).
    Thread-safe - can be called from ThreadPoolExecutor.
    """
    try:
        ip_address = data.get('ip', '').strip() if data.get('ip') else None
        device_type_id = data.get('device_type')
        role_id = data.get('role')
        site_id = data.get('site', 1)
        username = data.get('username', '')
        password = data.get('password', '')

        # Validation
        if not ip_address:
            return {'status': 'error', 'error': 'ip is required', 'field': 'ip'}, 400

        ip_version = detect_ip_version(ip_address)
        if not ip_version:
            return {'status': 'error', 'error': f'Invalid IP address format: {ip_address}', 'field': 'ip'}, 400

        if not device_type_id:
            return {'status': 'error', 'error': 'device_type is required', 'field': 'device_type'}, 400

        if not role_id:
            return {'status': 'error', 'error': 'role is required', 'field': 'role'}, 400

        # Check duplicates
        device_check = check_device_exists(ip_address)
        if device_check['exists']:
            return {
                'status': 'error', 'error': 'Device already exists with this IP',
                'field': 'ip', 'ip_address': ip_address,
                'existing': {
                    'device_id': device_check.get('device_id'),
                    'device_name': device_check.get('device_name'),
                    'primary_ip': device_check.get('primary_ip')
                }
            }, 409

        ip_check = check_ip_exists(ip_address)
        if ip_check['exists']:
            return {
                'status': 'error', 'error': 'IP address already exists',
                'field': 'ip', 'ip_address': ip_address,
                'existing': {
                    'ip_id': ip_check.get('ip_id'),
                    'device_id': ip_check.get('device_id'),
                    'device_name': ip_check.get('device_name')
                }
            }, 409

        # Create device
        device_name = ip_address
        encrypted_password = encrypt_password(password) if password else ''

        custom_fields = {}
        if username:
            custom_fields['username'] = username
        if encrypted_password:
            custom_fields['password'] = encrypted_password

        device_payload = {
            'name': device_name,
            'device_type': device_type_id,
            'role': role_id,
            'site': site_id,
            'status': 'active',
            'custom_fields': custom_fields
        }

        device_response = session.post(f"{NETBOX_URL}/api/dcim/devices/", json=device_payload)

        if device_response.status_code not in [200, 201] and 'custom field' in device_response.text.lower():
            del device_payload['custom_fields']
            device_response = session.post(f"{NETBOX_URL}/api/dcim/devices/", json=device_payload)

        if device_response.status_code not in [200, 201]:
            return {'status': 'error', 'error': 'Failed to create device', 'details': device_response.text}, 500

        device_data = device_response.json()
        device_id = device_data['id']

        # Create interface
        interface_response = session.post(
            f"{NETBOX_URL}/api/dcim/interfaces/",
            json={'device': device_id, 'name': 'mgmt0', 'type': 'virtual'}
        )

        interface_id = None
        interface_error = None
        if interface_response.status_code in [200, 201]:
            interface_id = interface_response.json()['id']
        else:
            interface_error = interface_response.text

        # Create IP address
        cidr = f"{ip_address}/32" if ip_version == 'ipv4' else f"{ip_address}/128"
        ip_payload = {'address': cidr, 'status': 'active'}
        if interface_id:
            ip_payload['assigned_object_type'] = 'dcim.interface'
            ip_payload['assigned_object_id'] = interface_id

        ip_response = session.post(f"{NETBOX_URL}/api/ipam/ip-addresses/", json=ip_payload)

        ip_id = None
        ip_create_error = None
        if ip_response.status_code in [200, 201]:
            ip_id = ip_response.json()['id']
        else:
            ip_create_error = ip_response.text

        # Set primary IP
        primary_ip_set = False
        primary_field = 'primary_ip4' if ip_version == 'ipv4' else 'primary_ip6'
        assign_error = None

        if ip_id:
            assign_response = session.patch(
                f"{NETBOX_URL}/api/dcim/devices/{device_id}/",
                json={primary_field: ip_id}
            )
            primary_ip_set = assign_response.status_code == 200
            if not primary_ip_set:
                assign_error = assign_response.text

        return {
            'status': 'success',
            'message': 'Device onboarded successfully',
            'data': {
                'device_id': device_id,
                'device_name': device_name,
                'ip_address': ip_address,
                'device_type': device_type_id,
                'role': role_id,
                'site': site_id,
                'onboard_type': 'manual',
                'reachable': None,
                'authentication': None,
                'management': None,
            }
        }, 201

    except Exception as e:
        return {'status': 'error', 'error': str(e)}, 500


def _onboard_dhcp(data):
    """
    Core DHCP onboarding logic. Returns (result_dict, status_code).
    Thread-safe - can be called from ThreadPoolExecutor.
    """
    try:
        mac_address = data.get('mac', '').strip() if data.get('mac') else None
        ip_address = data.get('ip', '').strip() if data.get('ip') else None
        device_type_id = data.get('device_type')
        role_id = data.get('role')
        site_id = data.get('site', 1)
        hostname = data.get('hostname', '').strip() if data.get('hostname') else None
        username = data.get('username', '')
        password = data.get('password', '')

        # Validation
        if not mac_address:
            return {'status': 'error', 'error': 'mac is required for DHCP onboarding', 'field': 'mac'}, 400

        if not is_valid_mac(mac_address):
            return {'status': 'error', 'error': f'Invalid MAC address format: {mac_address}', 'field': 'mac'}, 400

        mac_address = normalize_mac(mac_address)

        if not device_type_id:
            return {'status': 'error', 'error': 'device_type is required', 'field': 'device_type'}, 400

        if not role_id:
            return {'status': 'error', 'error': 'role is required', 'field': 'role'}, 400

        ip_version = None
        if ip_address:
            ip_version = detect_ip_version(ip_address)
            if not ip_version:
                return {'status': 'error', 'error': f'Invalid IP address format: {ip_address}', 'field': 'ip'}, 400

        # Check duplicate MAC
        device_check = check_device_exists(mac_address)
        if device_check['exists']:
            return {
                'status': 'error', 'error': 'Device already exists with this MAC',
                'field': 'mac', 'mac_address': mac_address,
                'existing': {
                    'device_id': device_check.get('device_id'),
                    'device_name': device_check.get('device_name'),
                    'primary_ip': device_check.get('primary_ip')
                }
            }, 409

        # Check IP reachability for reassignment
        existing_ip_id = None
        if ip_address:
            ip_device_check = check_ip_device_reachable(ip_address)
            if ip_device_check['exists']:
                if not ip_device_check['can_reassign']:
                    return {
                        'status': 'error', 'error': 'IP is assigned to an active device',
                        'field': 'ip', 'ip_address': ip_address,
                        'existing': {
                            'device_id': ip_device_check.get('device_id'),
                            'device_name': ip_device_check.get('device_name'),
                            'device_reachable': ip_device_check.get('device_reachable'),
                            'reason': ip_device_check.get('reason')
                        }
                    }, 409
                else:
                    existing_ip_id = ip_device_check.get('ip_id')

        # Create device
        device_name = mac_address
        encrypted_password = encrypt_password(password) if password else ''

        custom_fields = {}
        if hostname:
            custom_fields['hostname'] = hostname
        if username:
            custom_fields['username'] = username
        if encrypted_password:
            custom_fields['password'] = encrypted_password

        device_payload = {
            'name': device_name,
            'device_type': device_type_id,
            'role': role_id,
            'site': site_id,
            'status': 'active',
            'custom_fields': custom_fields
        }

        device_response = session.post(f"{NETBOX_URL}/api/dcim/devices/", json=device_payload)

        if device_response.status_code not in [200, 201] and 'custom field' in device_response.text.lower():
            del device_payload['custom_fields']
            device_response = session.post(f"{NETBOX_URL}/api/dcim/devices/", json=device_payload)

        if device_response.status_code not in [200, 201]:
            return {'status': 'error', 'error': 'Failed to create device', 'details': device_response.text}, 500

        device_data = device_response.json()
        device_id = device_data['id']

        # Create interface with MAC
        interface_response = session.post(
            f"{NETBOX_URL}/api/dcim/interfaces/",
            json={'device': device_id, 'name': 'eth0', 'type': 'other', 'mac_address': mac_address}
        )

        interface_id = None
        interface_error = None
        interface_mac = None
        if interface_response.status_code in [200, 201]:
            interface_data = interface_response.json()
            interface_id = interface_data['id']
            interface_mac = interface_data.get('mac_address')
        else:
            interface_error = interface_response.text

        # Handle IP address
        ip_id = None
        ip_create_error = None
        ip_reassigned = False
        primary_ip_set = False
        assign_error = None

        if ip_address and interface_id:
            if existing_ip_id:
                reassign_response = session.patch(
                    f"{NETBOX_URL}/api/ipam/ip-addresses/{existing_ip_id}/",
                    json={
                        'assigned_object_type': 'dcim.interface',
                        'assigned_object_id': interface_id,
                        'status': 'dhcp'
                    }
                )
                if reassign_response.status_code == 200:
                    ip_id = existing_ip_id
                    ip_reassigned = True
                else:
                    ip_create_error = f"Failed to reassign IP: {reassign_response.text}"
            else:
                cidr = f"{ip_address}/32" if ip_version == 'ipv4' else f"{ip_address}/128"
                ip_payload = {
                    'address': cidr,
                    'status': 'dhcp',
                    'assigned_object_type': 'dcim.interface',
                    'assigned_object_id': interface_id
                }
                ip_response = session.post(f"{NETBOX_URL}/api/ipam/ip-addresses/", json=ip_payload)
                if ip_response.status_code in [200, 201]:
                    ip_id = ip_response.json()['id']
                else:
                    ip_create_error = ip_response.text

            if ip_id:
                primary_field = 'primary_ip4' if ip_version == 'ipv4' else 'primary_ip6'
                assign_response = session.patch(
                    f"{NETBOX_URL}/api/dcim/devices/{device_id}/",
                    json={primary_field: ip_id}
                )
                primary_ip_set = assign_response.status_code == 200
                if not primary_ip_set:
                    assign_error = assign_response.text

        return {
            'status': 'success',
            'message': 'Device onboarded via DHCP successfully',
            'data': {
                'device_id': device_id,
                'device_name': device_name,
                'mac_address': mac_address,
                'ip_address': ip_address,
                'device_type': device_type_id,
                'role': role_id,
                'site': site_id,
                'onboard_type': 'dhcp',
                'reachable': None,
                'authentication': None,
                'management': None,
            }
        }, 201

    except Exception as e:
        return {'status': 'error', 'error': str(e)}, 500


# =============================================================================
# MANUAL ONBOARDING (IP Required)
# =============================================================================
@app.route('/api/onboard', methods=['POST'])
def onboard_device():
    """Manual Device Onboarding - IP address required"""
    data = request.get_json()
    result, status_code = _onboard_manual(data)
    return jsonify(result), status_code


# =============================================================================
# DHCP ONBOARDING (MAC Required) - Future Implementation
# =============================================================================
@app.route('/api/onboard/dhcp', methods=['POST'])
def onboard_device_dhcp():
    """DHCP Device Onboarding - MAC address required"""
    data = request.get_json()
    result, status_code = _onboard_dhcp(data)
    return jsonify(result), status_code


# =============================================================================
# BULK ONBOARDING (Async with batch tracking)
# =============================================================================
def _process_single_device(index, device_data):
    """Process a single device for bulk onboarding. Returns (index, result, status_code)."""
    has_mac = bool(device_data.get('mac', '').strip() if device_data.get('mac') else None)
    has_ip = bool(device_data.get('ip', '').strip() if device_data.get('ip') else None)

    if has_mac and not has_ip:
        result, status_code = _onboard_dhcp(device_data)
    else:
        result, status_code = _onboard_manual(device_data)

    return index, result, status_code


def _parse_csv_devices(csv_text):
    """Parse CSV text into list of device dicts."""
    devices = []
    reader = csv.DictReader(io.StringIO(csv_text))
    for row in reader:
        device = {}
        for key, value in row.items():
            if value is None or value.strip() == '':
                continue
            key = key.strip().lower()
            if key in ('device_type', 'role', 'site'):
                try:
                    device[key] = int(value.strip())
                except ValueError:
                    device[key] = value.strip()
            else:
                device[key] = value.strip()
        if device:
            devices.append(device)
    return devices


def _run_batch(batch_id, devices):
    """
    Background worker: processes all devices in a batch using thread pool.
    Updates batch state in real-time so frontend can poll progress.
    """
    global bulk_in_progress
    batch = _batches[batch_id]

    try:
        with ThreadPoolExecutor(max_workers=BULK_MAX_WORKERS) as pool:
            futures = {
                pool.submit(_process_single_device, i, device): i
                for i, device in enumerate(devices)
            }

            for future in as_completed(futures):
                try:
                    index, result, status_code = future.result()
                except Exception as e:
                    index = futures[future]
                    result = {'status': 'error', 'error': str(e)}
                    status_code = 500

                entry = dict(result)
                entry['_index'] = index
                entry['_status_code'] = status_code

                with _batches_lock:
                    batch['results'][index] = entry
                    batch['processed'] += 1

                    if result.get('status') == 'success':
                        batch['successful'] += 1
                        device_id = result.get('data', {}).get('device_id')
                        if device_id:
                            batch['device_ids'].append(device_id)
                    else:
                        batch['failed'] += 1

                    batch['progress_percent'] = round(
                        (batch['processed'] / batch['total']) * 100, 1
                    )

                    logger.info(f"[Batch {batch_id[:8]}] {batch['processed']}/{batch['total']} "
                                f"({batch['progress_percent']}%) - "
                                f"ok={batch['successful']} fail={batch['failed']}")

        # Batch complete
        with _batches_lock:
            batch['status'] = 'completed'
            batch['finished_at'] = datetime.utcnow().isoformat() + 'Z'
            batch['elapsed_seconds'] = round(time.time() - batch['_start_time'], 2)

        logger.info(f"[Batch {batch_id[:8]}] COMPLETED: {batch['successful']}/{batch['total']} "
                     f"successful in {batch['elapsed_seconds']}s")

    except Exception as e:
        with _batches_lock:
            batch['status'] = 'failed'
            batch['error'] = str(e)
            batch['finished_at'] = datetime.utcnow().isoformat() + 'Z'
            batch['elapsed_seconds'] = round(time.time() - batch['_start_time'], 2)
        logger.error(f"[Batch {batch_id[:8]}] FAILED: {e}")

    finally:
        bulk_in_progress = False
        bulk_lock.release()


@app.route('/api/onboard/bulk', methods=['POST'])
def onboard_bulk():
    """
    Async Bulk Device Onboarding - returns batch_id immediately.

    Accepts:
      1. JSON: {"devices": [{...}, {...}]}
      2. CSV file upload (multipart/form-data, field name: "file")
      3. CSV text in body (Content-Type: text/csv)

    Returns 202 with batch_id. Poll GET /api/onboard/bulk/<batch_id> for progress.
    """
    global bulk_in_progress

    # Prevent concurrent bulk operations
    if not bulk_lock.acquire(blocking=False):
        # Find the active batch to return its ID
        active_batch_id = None
        for bid, b in _batches.items():
            if b['status'] == 'processing':
                active_batch_id = bid
                break
        return jsonify({
            'status': 'error',
            'error': 'Another bulk onboarding operation is in progress',
            'active_batch_id': active_batch_id
        }), 429

    try:
        bulk_in_progress = True

        # Parse input
        devices = []
        content_type = request.content_type or ''

        if 'multipart/form-data' in content_type:
            file = request.files.get('file')
            if not file:
                bulk_in_progress = False
                bulk_lock.release()
                return jsonify({'status': 'error', 'error': 'No file uploaded. Use field name "file"'}), 400
            csv_text = file.read().decode('utf-8')
            devices = _parse_csv_devices(csv_text)
        elif 'text/csv' in content_type:
            csv_text = request.get_data(as_text=True)
            devices = _parse_csv_devices(csv_text)
        else:
            data = request.get_json()
            if not data:
                bulk_in_progress = False
                bulk_lock.release()
                return jsonify({'status': 'error', 'error': 'Request body is empty'}), 400
            devices = data.get('devices', [])

        if not devices:
            bulk_in_progress = False
            bulk_lock.release()
            return jsonify({'status': 'error', 'error': 'No devices provided'}), 400

        if len(devices) > BULK_MAX_DEVICES:
            bulk_in_progress = False
            bulk_lock.release()
            return jsonify({
                'status': 'error',
                'error': f'Too many devices. Maximum is {BULK_MAX_DEVICES}, got {len(devices)}'
            }), 400

        # Create batch
        batch_id = str(uuid.uuid4())
        now = datetime.utcnow().isoformat() + 'Z'

        batch = {
            'batch_id': batch_id,
            'status': 'processing',
            'total': len(devices),
            'processed': 0,
            'successful': 0,
            'failed': 0,
            'progress_percent': 0.0,
            'workers': BULK_MAX_WORKERS,
            'started_at': now,
            'finished_at': None,
            'elapsed_seconds': None,
            'error': None,
            'device_ids': [],
            'results': [None] * len(devices),
            '_start_time': time.time(),
        }

        with _batches_lock:
            _batches[batch_id] = batch

        # Start background processing thread
        thread = threading.Thread(
            target=_run_batch,
            args=(batch_id, devices),
            daemon=True
        )
        thread.start()

        logger.info(f"[Batch {batch_id[:8]}] Started: {len(devices)} devices with {BULK_MAX_WORKERS} workers")

        return jsonify({
            'status': 'accepted',
            'batch_id': batch_id,
            'total': len(devices),
            'workers': BULK_MAX_WORKERS,
            'message': f'Bulk onboarding started. Poll GET /api/onboard/bulk/{batch_id} for progress.'
        }), 202

    except Exception as e:
        bulk_in_progress = False
        bulk_lock.release()
        return jsonify({'status': 'error', 'error': str(e)}), 500


@app.route('/api/onboard/bulk/<batch_id>', methods=['GET'])
def get_batch_status(batch_id):
    """
    Get batch progress. Frontend polls this every 2-5 seconds.

    Response:
    {
        "batch_id": "abc-123",
        "status": "processing" | "completed" | "failed",
        "total": 1000,
        "processed": 450,
        "successful": 448,
        "failed": 2,
        "progress_percent": 45.0,
        "started_at": "...",
        "finished_at": null,
        "elapsed_seconds": null,
        "device_ids": [45, 46, 47, ...],
        "results": [...]       // only included when completed or if ?results=true
    }
    """
    batch = _batches.get(batch_id)
    if not batch:
        return jsonify({'status': 'error', 'error': 'Batch not found'}), 404

    include_results = (
        request.args.get('results', 'false').lower() == 'true'
        or batch['status'] in ('completed', 'failed')
    )

    response = {
        'batch_id': batch['batch_id'],
        'status': batch['status'],
        'total': batch['total'],
        'processed': batch['processed'],
        'successful': batch['successful'],
        'failed': batch['failed'],
        'progress_percent': batch['progress_percent'],
        'workers': batch['workers'],
        'started_at': batch['started_at'],
        'finished_at': batch['finished_at'],
        'elapsed_seconds': batch.get('elapsed_seconds') or round(time.time() - batch['_start_time'], 2),
        'device_ids': batch['device_ids'],
    }

    if batch.get('error'):
        response['error'] = batch['error']

    if include_results:
        response['results'] = batch['results']

    return jsonify(response)


@app.route('/api/onboard/bulk/batches', methods=['GET'])
def list_batches():
    """
    List all batches (active and recent). Used when user closes tab and comes back.

    Response:
    {
        "active": {...} or null,
        "recent": [{...}, {...}]    // last 10 completed batches
    }
    """
    active = None
    recent = []

    for batch_id, batch in _batches.items():
        summary = {
            'batch_id': batch['batch_id'],
            'status': batch['status'],
            'total': batch['total'],
            'processed': batch['processed'],
            'successful': batch['successful'],
            'failed': batch['failed'],
            'progress_percent': batch['progress_percent'],
            'started_at': batch['started_at'],
            'finished_at': batch['finished_at'],
            'elapsed_seconds': batch.get('elapsed_seconds') or round(time.time() - batch['_start_time'], 2),
        }

        if batch['status'] == 'processing':
            active = summary
        else:
            recent.append(summary)

    # Sort recent by start time descending, keep last 10
    recent.sort(key=lambda x: x['started_at'], reverse=True)
    recent = recent[:10]

    return jsonify({'active': active, 'recent': recent})


# =============================================================================
# VALIDATION ENDPOINTS
# =============================================================================
@app.route('/api/validate/ip', methods=['POST'])
def validate_ip():
    """Check if IP already exists"""
    try:
        data = request.get_json()
        ip_address = data.get('ip', '').strip() if data.get('ip') else None

        if not ip_address:
            return jsonify({'status': 'error', 'error': 'ip is required'}), 400

        ip_version = detect_ip_version(ip_address)
        if not ip_version:
            return jsonify({
                'status': 'error',
                'error': f'Invalid IP format: {ip_address}',
                'valid': False
            }), 400

        ip_check = check_ip_exists(ip_address)

        return jsonify({
            'status': 'exists' if ip_check['exists'] else 'available',
            'ip': ip_address,
            'ip_version': ip_version,
            'exists': ip_check['exists'],
            'can_create': not ip_check['exists'],
            'existing': ip_check if ip_check['exists'] else None
        }), 409 if ip_check['exists'] else 200

    except Exception as e:
        return jsonify({'status': 'error', 'error': str(e)}), 500


@app.route('/api/validate/mac', methods=['POST'])
def validate_mac():
    """Check if MAC already exists"""
    try:
        data = request.get_json()
        mac_address = data.get('mac', '').strip() if data.get('mac') else None

        if not mac_address:
            return jsonify({'status': 'error', 'error': 'mac is required'}), 400

        if not is_valid_mac(mac_address):
            return jsonify({
                'status': 'error',
                'error': f'Invalid MAC format: {mac_address}',
                'valid': False
            }), 400

        mac_address = normalize_mac(mac_address)
        mac_check = check_mac_exists(mac_address)

        return jsonify({
            'status': 'exists' if mac_check['exists'] else 'available',
            'mac': mac_address,
            'exists': mac_check['exists'],
            'can_create': not mac_check['exists'],
            'existing': mac_check if mac_check['exists'] else None
        }), 409 if mac_check['exists'] else 200

    except Exception as e:
        return jsonify({'status': 'error', 'error': str(e)}), 500


# =============================================================================
# HELPER ENDPOINTS
# =============================================================================
@app.route('/api/device-types', methods=['GET'])
def get_device_types():
    """Get list of available device types"""
    response = session.get(f"{NETBOX_URL}/api/dcim/device-types/")
    if response.status_code == 200:
        types = [{'id': dt['id'], 'name': dt['display']} for dt in response.json()['results']]
        return jsonify(types)
    return jsonify([]), response.status_code


@app.route('/api/device-roles', methods=['GET'])
def get_device_roles():
    """Get list of available device roles"""
    response = session.get(f"{NETBOX_URL}/api/dcim/device-roles/")
    if response.status_code == 200:
        roles = [{'id': r['id'], 'name': r['name']} for r in response.json()['results']]
        return jsonify(roles)
    return jsonify([]), response.status_code


@app.route('/api/sites', methods=['GET'])
def get_sites():
    """Get list of available sites"""
    response = session.get(f"{NETBOX_URL}/api/dcim/sites/")
    if response.status_code == 200:
        sites = [{'id': s['id'], 'name': s['name']} for s in response.json()['results']]
        return jsonify(sites)
    return jsonify([]), response.status_code


@app.route('/api/devices', methods=['GET'])
def get_all_devices():
    """
    Get all devices from NetBox inventory.
    Used by frontend to display the device table/inventory page.

    Query params:
        ?limit=50      (default 50, max 1000)
        ?offset=0      (for pagination)
        ?role=cpe      (filter by role slug)
        ?site=default-site  (filter by site slug)
        ?status=active (filter by status)

    Response:
    {
        "count": 250,
        "devices": [
            {
                "id": 45,
                "name": "192.168.1.181",
                "ip_address": "192.168.1.181",
                "device_type": "MaxLinear 10GE CPE",
                "role": "CPE",
                "site": "Default Site",
                "status": "active",
                "reachable": true,
                "authentication": true,
                "management": null
            }, ...
        ]
    }
    """
    limit = min(int(request.args.get('limit', 50)), 1000)
    offset = int(request.args.get('offset', 0))

    params = {'limit': limit, 'offset': offset}
    if request.args.get('role'):
        params['role'] = request.args.get('role')
    if request.args.get('site'):
        params['site'] = request.args.get('site')
    if request.args.get('status'):
        params['status'] = request.args.get('status')

    try:
        resp = session.get(f"{NETBOX_URL}/api/dcim/devices/", params=params)
        if resp.status_code != 200:
            return jsonify({'error': 'Failed to fetch devices', 'details': resp.text}), resp.status_code

        data = resp.json()
        devices = []

        for d in data.get('results', []):
            cf = d.get('custom_fields', {}) or {}

            # Extract IP
            ip_address = None
            if d.get('primary_ip4') and d['primary_ip4'].get('address'):
                ip_address = d['primary_ip4']['address'].split('/')[0]

            devices.append({
                'id': d['id'],
                'name': d.get('name', ''),
                'ip_address': ip_address,
                'device_type': d.get('device_type', {}).get('display', ''),
                'role': d.get('role', {}).get('name', ''),
                'site': d.get('site', {}).get('name', ''),
                'status': d.get('status', {}).get('value', ''),
                'reachable': cf.get('reachable'),
                'authentication': cf.get('authentication'),
                'management': cf.get('management'),
            })

        return jsonify({
            'count': data.get('count', 0),
            'devices': devices,
        })

    except Exception as e:
        return jsonify({'error': str(e)}), 500


@app.route('/api/devices/<int:device_id>/credentials', methods=['PATCH'])
def update_device_credentials(device_id):
    """
    Update device credentials and re-trigger SSH validation.

    When the user changes username/password:
      1. Update encrypted credentials in NetBox custom_fields
      2. Reset reachable/authentication to null → device goes back to "pending"
      3. The NetBox update fires an "updated" webhook
      4. Webhook handler sees reachable=null → does NOT skip → re-validates via Server2
      5. Frontend polls /api/devices/status to see the result

    Request:  { "username": "admin", "password": "newpass123" }
    Response: { "status": "success", "data": { "device_id": 45, "reachable": null, "authentication": null } }
    """
    data = request.get_json()
    if not data:
        return jsonify({'status': 'error', 'error': 'Request body is empty'}), 400

    username = data.get('username')
    password = data.get('password')

    if not username and not password:
        return jsonify({'status': 'error', 'error': 'At least one of username or password is required'}), 400

    try:
        # Verify device exists
        resp = session.get(f"{NETBOX_URL}/api/dcim/devices/{device_id}/")
        if resp.status_code == 404:
            return jsonify({'status': 'error', 'error': 'Device not found'}), 404
        if resp.status_code != 200:
            return jsonify({'status': 'error', 'error': 'Failed to fetch device', 'details': resp.text}), resp.status_code

        device = resp.json()
        existing_cf = device.get('custom_fields', {}) or {}

        # Build custom_fields update: new credentials + reset validation
        custom_fields = {
            'reachable': None,
            'authentication': None,
        }

        if username is not None:
            custom_fields['username'] = username
        if password is not None:
            custom_fields['password'] = encrypt_password(password)

        # PATCH device in NetBox
        patch_resp = session.patch(
            f"{NETBOX_URL}/api/dcim/devices/{device_id}/",
            json={'custom_fields': custom_fields}
        )

        if patch_resp.status_code != 200:
            return jsonify({'status': 'error', 'error': 'Failed to update device', 'details': patch_resp.text}), 500

        logger.info(f"Credentials updated for device {device_id} ({device.get('name', '')}). "
                    f"Validation reset to pending - webhook will re-trigger SSH validation.")

        return jsonify({
            'status': 'success',
            'message': 'Credentials updated. SSH validation will re-run automatically.',
            'data': {
                'device_id': device_id,
                'device_name': device.get('name', ''),
                'reachable': None,
                'authentication': None,
            }
        })

    except Exception as e:
        return jsonify({'status': 'error', 'error': str(e)}), 500


@app.route('/api/devices/<int:device_id>/revalidate', methods=['POST'])
def revalidate_device(device_id):
    """
    Re-trigger SSH validation using existing stored credentials.

    Use cases:
      - Password was changed on the physical device, user wants to verify
      - Device was unreachable earlier, user wants to retry
      - Routine re-check after maintenance

    Resets reachable/authentication to null → NetBox webhook fires →
    webhook handler re-validates via Server2 with the credentials already stored.

    Request:  POST /api/devices/45/revalidate  (no body needed)
    Response: { "status": "success", "data": { "device_id": 45, "reachable": null, "authentication": null } }
    """
    try:
        resp = session.get(f"{NETBOX_URL}/api/dcim/devices/{device_id}/")
        if resp.status_code == 404:
            return jsonify({'status': 'error', 'error': 'Device not found'}), 404
        if resp.status_code != 200:
            return jsonify({'status': 'error', 'error': 'Failed to fetch device', 'details': resp.text}), resp.status_code

        device = resp.json()

        # Reset validation fields → triggers webhook → re-validates
        patch_resp = session.patch(
            f"{NETBOX_URL}/api/dcim/devices/{device_id}/",
            json={'custom_fields': {'reachable': None, 'authentication': None}}
        )

        if patch_resp.status_code != 200:
            return jsonify({'status': 'error', 'error': 'Failed to reset validation', 'details': patch_resp.text}), 500

        logger.info(f"Re-validation triggered for device {device_id} ({device.get('name', '')})")

        return jsonify({
            'status': 'success',
            'message': 'Re-validation triggered. SSH validation will re-run with existing credentials.',
            'data': {
                'device_id': device_id,
                'device_name': device.get('name', ''),
                'reachable': None,
                'authentication': None,
            }
        })

    except Exception as e:
        return jsonify({'status': 'error', 'error': str(e)}), 500


@app.route('/api/devices/revalidate-all', methods=['POST'])
def revalidate_all_devices():
    """
    Bulk re-validate: reset reachable/authentication for ALL devices (or filtered).
    Each reset fires a NetBox webhook → webhook handler re-validates via Server2.

    Use case: detect password changes made directly on physical devices.

    Optional filters in body:
      { "role": "cpe", "site": "default-site", "device_ids": [1,2,3] }
    No body = re-validate ALL devices.

    Response: { "status": "success", "reset_count": 150, "device_ids": [...] }
    """
    data = request.get_json() or {}
    filter_ids = data.get('device_ids')
    filter_role = data.get('role')
    filter_site = data.get('site')

    try:
        # If specific device_ids provided, use those directly
        if filter_ids:
            target_ids = filter_ids
        else:
            # Fetch all devices (paginated) with optional filters
            target_ids = []
            params = {'limit': 1000, 'offset': 0}
            if filter_role:
                params['role'] = filter_role
            if filter_site:
                params['site'] = filter_site

            while True:
                resp = session.get(f"{NETBOX_URL}/api/dcim/devices/", params=params)
                if resp.status_code != 200:
                    return jsonify({'status': 'error', 'error': 'Failed to fetch devices', 'details': resp.text}), 500

                page = resp.json()
                for d in page.get('results', []):
                    target_ids.append(d['id'])

                if not page.get('next'):
                    break
                params['offset'] += params['limit']

        if not target_ids:
            return jsonify({'status': 'success', 'message': 'No devices found', 'reset_count': 0}), 200

        # Reset validation for each device (batched PATCHes)
        reset_count = 0
        failed_ids = []

        for device_id in target_ids:
            try:
                patch_resp = session.patch(
                    f"{NETBOX_URL}/api/dcim/devices/{device_id}/",
                    json={'custom_fields': {'reachable': None, 'authentication': None}}
                )
                if patch_resp.status_code == 200:
                    reset_count += 1
                else:
                    failed_ids.append(device_id)
            except Exception:
                failed_ids.append(device_id)

        logger.info(f"Bulk re-validate: reset {reset_count}/{len(target_ids)} devices. "
                    f"Webhooks will trigger SSH re-validation for each.")

        result = {
            'status': 'success',
            'message': f'Re-validation triggered for {reset_count} devices. SSH checks will run automatically.',
            'reset_count': reset_count,
            'total_requested': len(target_ids),
            'device_ids': target_ids,
        }
        if failed_ids:
            result['failed_ids'] = failed_ids

        return jsonify(result)

    except Exception as e:
        return jsonify({'status': 'error', 'error': str(e)}), 500


@app.route('/api/devices/status', methods=['POST'])
def device_status():
    """
    Get validation status for a list of device IDs.
    Frontend polls this after bulk onboard to track reachable/authentication progress.

    Request:  {"device_ids": [30, 31, 29]}
    Response: {
        "devices": [
            {"id": 30, "name": "192.168.1.171", "reachable": true, "authentication": true, "management": null},
            {"id": 31, "name": "192.168.1.172", "reachable": null, "authentication": null, "management": null},
            ...
        ]
    }
    """
    data = request.get_json()
    device_ids = data.get('device_ids', [])

    if not device_ids:
        return jsonify({'error': 'device_ids required'}), 400

    devices = []

    for device_id in device_ids:
        try:
            resp = session.get(f"{NETBOX_URL}/api/dcim/devices/{device_id}/")
            if resp.status_code != 200:
                devices.append({'id': device_id, 'error': 'not found'})
                continue

            device = resp.json()
            cf = device.get('custom_fields', {}) or {}

            devices.append({
                'id': device_id,
                'name': device.get('name', ''),
                'reachable': cf.get('reachable'),
                'authentication': cf.get('authentication'),
                'management': cf.get('management'),
            })
        except Exception as e:
            devices.append({'id': device_id, 'error': str(e)})

    return jsonify({'devices': devices})


@app.route('/health', methods=['GET'])
def health():
    """Health check endpoint"""
    return jsonify({
        'status': 'healthy',
        'netbox_url': NETBOX_URL,
        'primary_key': 'device_id (auto-generated)',
        'supported_modes': ['manual (IP)', 'dhcp (MAC)']
    })


@app.route('/', methods=['GET'])
def index():
    """API documentation"""
    return jsonify({
        'service': 'Device Onboarding API',
        'version': '3.0',
        'primary_key': 'device_id (auto-generated by NetBox)',
        'endpoints': {
            'POST /api/onboard': 'Manual onboarding (IP required)',
            'POST /api/onboard/dhcp': 'DHCP onboarding (MAC required)',
            'POST /api/onboard/bulk': 'Bulk onboarding - returns batch_id (202)',
            'GET /api/onboard/bulk/<batch_id>': 'Get batch progress (poll every 2-5s)',
            'GET /api/onboard/bulk/batches': 'List active + recent batches (tab recovery)',
            'POST /api/validate/ip': 'Check if IP exists',
            'POST /api/validate/mac': 'Check if MAC exists',
            'PATCH /api/devices/<id>/credentials': 'Update credentials & re-trigger SSH validation',
            'POST /api/devices/<id>/revalidate': 'Re-trigger SSH validation for one device',
            'POST /api/devices/revalidate-all': 'Bulk re-validate all devices (detect password changes on devices)',
            'POST /api/devices/status': 'Get SSH validation status for device IDs',
            'GET /api/device-types': 'List device types',
            'GET /api/device-roles': 'List device roles',
            'GET /api/sites': 'List sites',
            'GET /health': 'Health check'
        },
        'manual_onboard': {
            'endpoint': 'POST /api/onboard',
            'payload': {
                'ip': '192.168.1.100 (Required - IPv4 or IPv6)',
                'device_type': '1 (Required)',
                'role': '1 (Required)',
                'site': '1 (Optional, default: 1)',
                'username': 'admin (Optional)',
                'password': 'secret123 (Optional, encrypted)'
            }
        },
        'dhcp_onboard': {
            'endpoint': 'POST /api/onboard/dhcp',
            'payload': {
                'mac': 'AA:BB:CC:DD:EE:FF (Required)',
                'ip': '192.168.1.100 (Optional - DHCP assigned)',
                'device_type': '1 (Required)',
                'role': '1 (Required)',
                'site': '1 (Optional)',
                'hostname': 'device-001 (Optional)'
            }
        },
        'bulk_onboard': {
            'endpoint': 'POST /api/onboard/bulk',
            'workers': BULK_MAX_WORKERS,
            'max_devices': BULK_MAX_DEVICES,
            'formats': ['JSON', 'CSV file upload', 'CSV text'],
            'json_payload': {
                'devices': [
                    {'ip': '192.168.1.10', 'device_type': 1, 'role': 1, 'username': 'admin', 'password': 'pass'},
                    {'mac': 'AA:BB:CC:DD:EE:FF', 'device_type': 1, 'role': 1}
                ]
            },
            'csv_headers': 'ip,device_type,role,site,username,password,mac,hostname'
        }
    })


if __name__ == '__main__':
    print(f"""
================================================================================
Device Onboarding API Service v3.0
================================================================================
NetBox URL: {NETBOX_URL}
Primary Key: device_id (auto-generated by NetBox)
Bulk Workers: {BULK_MAX_WORKERS} | Max Devices: {BULK_MAX_DEVICES}

ENDPOINTS:
---------------------------------------------------------------------------
Manual Onboarding (IP required):
  POST /api/onboard
  Payload: {{"ip": "192.168.1.100", "device_type": 1, "role": 1}}

DHCP Onboarding (MAC required):
  POST /api/onboard/dhcp
  Payload: {{"mac": "AA:BB:CC:DD:EE:FF", "device_type": 1, "role": 1}}

Bulk Onboarding (JSON or CSV):
  POST /api/onboard/bulk
  JSON:  {{"devices": [{{"ip": "192.168.1.10", "device_type": 1, "role": 1}}]}}
  CSV:   curl -F "file=@devices.csv" http://localhost:5001/api/onboard/bulk

Validation:
  POST /api/validate/ip   - Check if IP exists
  POST /api/validate/mac  - Check if MAC exists

Helpers:
  GET /api/device-types   - List device types
  GET /api/device-roles   - List device roles
  GET /api/sites          - List sites
  GET /health             - Health check
================================================================================
""")
    app.run(host='0.0.0.0', port=5001, debug=True)
